name: geojson
description: GeoJSON is a format for encoding a variety of geographic data structures.
version: 1.0.0
repository: https://github.com/xclud/dart_geojson
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  latlng: ^0.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
